
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGINTABLE CLOSEDATA CLOSENOBR CLOSEROW CLOSETHEAD CONTENT GARBAGE OPENDATA OPENNOBR OPENROW OPENTHEADstart : BEGINTABLE dump OPENTHEAD dump CLOSETHEAD GARBAGE handlerowdump : GARBAGE dump\n            | CONTENT dump\n            | OPENROW dump\n            | CLOSEROW dump\n            | OPENNOBR dump\n            | CLOSENOBR dump\n            | emptyreduntant : OPENDATA reduntant\n                 | CONTENT reduntant\n                 | CLOSEDATA reduntant\n                 | GARBAGE reduntant\n                 | emptyempty :handlerow : OPENROW handlecontent CLOSEROW handlerow\n                 | emptyhandlecontent : datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell reduntantdatacell : OPENDATA CLOSEDATA\n                | OPENDATA CONTENT CLOSEDATA\n                | OPENDATA CONTENT CONTENT CLOSEDATA\n                | OPENDATA OPENNOBR CLOSENOBR CLOSEDATA\n                | OPENDATA OPENNOBR CONTENT CLOSENOBR CLOSEDATA\n                | OPENDATA GARBAGE CONTENT GARBAGE CLOSEDATA\n                | OPENDATA GARBAGE CONTENT CONTENT GARBAGE CLOSEDATA\n                | OPENDATA GARBAGE CONTENT CONTENT CONTENT GARBAGE CLOSEDATA'
    
_lr_action_items = {'BEGINTABLE':([0,],[2,]),'$end':([1,20,21,23,27,33,],[0,-14,-1,-16,-14,-15,]),'GARBAGE':([2,4,5,6,7,8,9,11,19,26,29,36,39,41,42,45,47,48,50,52,55,62,64,65,66,67,],[4,4,4,4,4,4,4,4,20,32,-18,-19,44,-20,-21,49,-22,-23,53,-24,-25,67,67,67,67,67,]),'CONTENT':([2,4,5,6,7,8,9,11,26,29,30,31,32,36,39,41,42,45,47,48,52,55,62,64,65,66,67,],[5,5,5,5,5,5,5,5,30,-18,35,38,39,-19,45,-20,-21,50,-22,-23,-24,-25,65,65,65,65,65,]),'OPENROW':([2,4,5,6,7,8,9,11,20,27,],[6,6,6,6,6,6,6,6,22,22,]),'CLOSEROW':([2,4,5,6,7,8,9,11,24,29,36,41,42,47,48,52,55,62,63,64,65,66,67,68,69,70,71,72,],[7,7,7,7,7,7,7,7,27,-18,-19,-20,-21,-22,-23,-24,-25,-14,-17,-14,-14,-14,-14,-13,-9,-10,-11,-12,]),'OPENNOBR':([2,4,5,6,7,8,9,11,26,],[8,8,8,8,8,8,8,8,31,]),'CLOSENOBR':([2,4,5,6,7,8,9,11,31,38,],[9,9,9,9,9,9,9,9,37,43,]),'OPENTHEAD':([2,3,4,5,6,7,8,9,10,12,13,14,15,16,17,],[-14,11,-14,-14,-14,-14,-14,-14,-8,-2,-3,-4,-5,-6,-7,]),'CLOSETHEAD':([4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,],[-14,-14,-14,-14,-14,-14,-8,-14,-2,-3,-4,-5,-6,-7,19,]),'OPENDATA':([22,25,28,29,34,36,40,41,42,46,47,48,51,52,54,55,56,57,58,59,60,61,62,64,65,66,67,],[26,26,26,-18,26,-19,26,-20,-21,26,-22,-23,26,-24,26,-25,26,26,26,26,26,26,64,64,64,64,64,]),'CLOSEDATA':([26,29,30,35,36,37,41,42,43,44,47,48,49,52,53,55,62,64,65,66,67,],[29,-18,36,41,-19,42,-20,-21,47,48,-22,-23,52,-24,55,-25,66,66,66,66,66,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'dump':([2,4,5,6,7,8,9,11,],[3,12,13,14,15,16,17,18,]),'empty':([2,4,5,6,7,8,9,11,20,27,62,64,65,66,67,],[10,10,10,10,10,10,10,10,23,23,68,68,68,68,68,]),'handlerow':([20,27,],[21,33,]),'handlecontent':([22,],[24,]),'datacell':([22,25,28,34,40,46,51,54,56,57,58,59,60,61,],[25,28,34,40,46,51,54,56,57,58,59,60,61,62,]),'reduntant':([62,64,65,66,67,],[63,69,70,71,72,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> BEGINTABLE dump OPENTHEAD dump CLOSETHEAD GARBAGE handlerow','start',7,'p_start','module1.py',66),
  ('dump -> GARBAGE dump','dump',2,'p_dump','module1.py',69),
  ('dump -> CONTENT dump','dump',2,'p_dump','module1.py',70),
  ('dump -> OPENROW dump','dump',2,'p_dump','module1.py',71),
  ('dump -> CLOSEROW dump','dump',2,'p_dump','module1.py',72),
  ('dump -> OPENNOBR dump','dump',2,'p_dump','module1.py',73),
  ('dump -> CLOSENOBR dump','dump',2,'p_dump','module1.py',74),
  ('dump -> empty','dump',1,'p_dump','module1.py',75),
  ('reduntant -> OPENDATA reduntant','reduntant',2,'p_reduntant','module1.py',78),
  ('reduntant -> CONTENT reduntant','reduntant',2,'p_reduntant','module1.py',79),
  ('reduntant -> CLOSEDATA reduntant','reduntant',2,'p_reduntant','module1.py',80),
  ('reduntant -> GARBAGE reduntant','reduntant',2,'p_reduntant','module1.py',81),
  ('reduntant -> empty','reduntant',1,'p_reduntant','module1.py',82),
  ('empty -> <empty>','empty',0,'p_empty','module1.py',84),
  ('handlerow -> OPENROW handlecontent CLOSEROW handlerow','handlerow',4,'p_handlerow','module1.py',88),
  ('handlerow -> empty','handlerow',1,'p_handlerow','module1.py',89),
  ('handlecontent -> datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell datacell reduntant','handlecontent',15,'p_handlecontent','module1.py',92),
  ('datacell -> OPENDATA CLOSEDATA','datacell',2,'p_datacell','module1.py',99),
  ('datacell -> OPENDATA CONTENT CLOSEDATA','datacell',3,'p_datacell','module1.py',100),
  ('datacell -> OPENDATA CONTENT CONTENT CLOSEDATA','datacell',4,'p_datacell','module1.py',101),
  ('datacell -> OPENDATA OPENNOBR CLOSENOBR CLOSEDATA','datacell',4,'p_datacell','module1.py',102),
  ('datacell -> OPENDATA OPENNOBR CONTENT CLOSENOBR CLOSEDATA','datacell',5,'p_datacell','module1.py',103),
  ('datacell -> OPENDATA GARBAGE CONTENT GARBAGE CLOSEDATA','datacell',5,'p_datacell','module1.py',104),
  ('datacell -> OPENDATA GARBAGE CONTENT CONTENT GARBAGE CLOSEDATA','datacell',6,'p_datacell','module1.py',105),
  ('datacell -> OPENDATA GARBAGE CONTENT CONTENT CONTENT GARBAGE CLOSEDATA','datacell',7,'p_datacell','module1.py',106),
]
