
# parsetab.py
# This file is automatically generated. Do not edit.
# pylint: disable=W,C,R
_tabversion = '3.10'

_lr_method = 'LALR'

_lr_signature = 'BEGIN CLOSEBOLD CLOSEH2 CLOSEH3 CLOSETABLE CONTENT END GARBAGE OPENBOLD OPENH2 OPENH3 OPENTABLEstart : summarysummary : BEGIN CONTENT CONTENT CLOSEH2 handletext summary\n               | empty\n    handletext : handleheader OPENTABLE skiptag CLOSETABLE handletext\n                  | OPENTABLE skiptag CLOSETABLE handletext\n                  | handlebold handlecontent handletext\n                  | empty \n    handlebold : OPENBOLD CONTENT CLOSEBOLD\n    handleheader : OPENH3 CONTENT CONTENT CLOSEH3\n    handlecontent : addcontent handlecontent\n                     | empty\n    addcontent : CONTENTskiptag : CONTENT skiptag\n                | OPENBOLD skiptag\n                | CLOSEBOLD skiptag\n                | empty\n    empty :'
    
_lr_action_items = {'BEGIN':([0,7,8,11,12,22,23,24,25,29,33,34,36,37,38,40,],[3,-17,3,-17,-7,-17,-17,-11,-12,-17,-6,-10,-8,-17,-5,-4,]),'$end':([0,1,2,4,7,8,11,12,15,22,23,24,25,29,33,34,36,37,38,40,],[-17,0,-1,-3,-17,-17,-17,-7,-2,-17,-17,-11,-12,-17,-6,-10,-8,-17,-5,-4,]),'CONTENT':([3,5,10,11,13,14,16,18,19,20,23,25,26,36,],[5,6,18,25,26,27,18,18,18,18,25,-12,35,-8,]),'CLOSEH2':([6,],[7,]),'OPENTABLE':([7,9,11,22,23,24,25,29,34,36,37,39,],[10,16,-17,10,-17,-11,-12,10,-10,-8,10,-9,]),'OPENH3':([7,11,22,23,24,25,29,34,36,37,],[13,-17,13,-17,-11,-12,13,-10,-8,13,]),'OPENBOLD':([7,10,11,16,18,19,20,22,23,24,25,29,34,36,37,],[14,19,-17,19,19,19,19,14,-17,-11,-12,14,-10,-8,14,]),'CLOSEBOLD':([10,16,18,19,20,27,],[20,20,20,20,20,36,]),'CLOSETABLE':([10,16,17,18,19,20,21,28,30,31,32,],[-17,-17,29,-17,-17,-17,-16,37,-13,-14,-15,]),'CLOSEH3':([35,],[39,]),}

_lr_action = {}
for _k, _v in _lr_action_items.items():
   for _x,_y in zip(_v[0],_v[1]):
      if not _x in _lr_action:  _lr_action[_x] = {}
      _lr_action[_x][_k] = _y
del _lr_action_items

_lr_goto_items = {'start':([0,],[1,]),'summary':([0,8,],[2,15,]),'empty':([0,7,8,10,11,16,18,19,20,22,23,29,37,],[4,12,4,21,24,21,21,21,21,12,24,12,12,]),'handletext':([7,22,29,37,],[8,33,38,40,]),'handleheader':([7,22,29,37,],[9,9,9,9,]),'handlebold':([7,22,29,37,],[11,11,11,11,]),'skiptag':([10,16,18,19,20,],[17,28,30,31,32,]),'handlecontent':([11,23,],[22,34,]),'addcontent':([11,23,],[23,23,]),}

_lr_goto = {}
for _k, _v in _lr_goto_items.items():
   for _x, _y in zip(_v[0], _v[1]):
       if not _x in _lr_goto: _lr_goto[_x] = {}
       _lr_goto[_x][_k] = _y
del _lr_goto_items
_lr_productions = [
  ("S' -> start","S'",1,None,None,None),
  ('start -> summary','start',1,'p_start','module2_singapore.py',66),
  ('summary -> BEGIN CONTENT CONTENT CLOSEH2 handletext summary','summary',6,'p_summary','module2_singapore.py',69),
  ('summary -> empty','summary',1,'p_summary','module2_singapore.py',70),
  ('handletext -> handleheader OPENTABLE skiptag CLOSETABLE handletext','handletext',5,'p_handletext','module2_singapore.py',74),
  ('handletext -> OPENTABLE skiptag CLOSETABLE handletext','handletext',4,'p_handletext','module2_singapore.py',75),
  ('handletext -> handlebold handlecontent handletext','handletext',3,'p_handletext','module2_singapore.py',76),
  ('handletext -> empty','handletext',1,'p_handletext','module2_singapore.py',77),
  ('handlebold -> OPENBOLD CONTENT CLOSEBOLD','handlebold',3,'p_handlebold','module2_singapore.py',81),
  ('handleheader -> OPENH3 CONTENT CONTENT CLOSEH3','handleheader',4,'p_handleheader','module2_singapore.py',88),
  ('handlecontent -> addcontent handlecontent','handlecontent',2,'p_handlecontent','module2_singapore.py',96),
  ('handlecontent -> empty','handlecontent',1,'p_handlecontent','module2_singapore.py',97),
  ('addcontent -> CONTENT','addcontent',1,'p_addcontent','module2_singapore.py',101),
  ('skiptag -> CONTENT skiptag','skiptag',2,'p_skiptag','module2_singapore.py',109),
  ('skiptag -> OPENBOLD skiptag','skiptag',2,'p_skiptag','module2_singapore.py',110),
  ('skiptag -> CLOSEBOLD skiptag','skiptag',2,'p_skiptag','module2_singapore.py',111),
  ('skiptag -> empty','skiptag',1,'p_skiptag','module2_singapore.py',112),
  ('empty -> <empty>','empty',0,'p_empty','module2_singapore.py',116),
]
